### ISSUE TITLE
Why is the app down?

### ISSUE THREAD

**Issue by tonystank420** [Docile-Alligator/Infinity-For-Reddit#1267]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

latest version

### Where did you get the app from

Google Play

### Android version

MiUI 11

### First occurred

Since 8 ish hours

### Steps to reproduce

1. Open the app

### Current behaviour

![Screenshot_2022-12-05-14-02-26-576_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/98456024/205590818-7b4e6bad-5834-4505-a8a3-64d8b9066a99.jpg)

**Comment by Eragonfr** [comment]
I have the same error. It happen only on ipv6-only network.
This is probably because Android doesn't implement an automatic way to redirect ipv4 traffic to ipv6 using nat64/dns64 or something like that.
There is a post from a reddit employee explaining what they did to get that working in the official app on r/ipv6

(Also I'm certain that this is an ipv6 vs ipv4 error because if you change your DNS to a DNS server that implement nat64 the problem is resolved.)

**Comment by tonystank420** [comment]
I updated the app on the playstore (even tho in the description they said not to update) and it works

**Comment by wrexxor** [comment]
I don't see a pending update in the Play Store, and am on IPv4 but I'm still seeing this issue
