### ISSUE TITLE
Bug: Redundant empty space on post headers

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#30]
posts in the fontpages often appears to have a long empty space after the options bar specially text posts and posts with external links...
![[a cropped screenshot of the app, showing the empty space]](https://user-images.githubusercontent.com/10854855/67639520-49b49180-f8cf-11e9-96cf-1a46f06dc58d.png)

if it helps with anything, the resolution is 480x740px, 72dpi

**Comment by Docile-Alligator** [comment]
Thank you for your feedback. I only encounter this issue in an emulator. I thought it was a bug related to the emulator itself. What version of Android do you use? Is it 5.1?

**Comment by Wilker-a** [comment]
yes, it is \^\^

**Comment by Docile-Alligator** [comment]
Hi! The problem is fixed now (maybe). Wait for the next update.

**Comment by Docile-Alligator** [comment]
Does the bug happen again after the update?

**Comment by Wilker-a** [comment]
the issue is apparently gone now \^u\^

**Comment by Docile-Alligator** [comment]
You are very welcome!

**Comment by sommv** [comment]
Hi! I'm also on Android 5.1, downloaded the app from the play store today and experience this exact problem. I guess it's maybe not solved after all? Or is the update not on the play store yet?

**Comment by Wilker-a** [comment]
i can confirm that the issue is back \^\^'

version 2.1.0 from the IzzyOnDroid F-Droid repository

**Comment by Docile-Alligator** [comment]
Yes. I know why this happens, but my new solution doesn't seem to work.
